# Generated by Django 5.0.3 on 2024-03-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, max_length=250, verbose_name='food')),
                ('calorie', models.CharField(blank=True, max_length=250, verbose_name='calorie')),
                ('description', models.CharField(blank=True, max_length=450, verbose_name='description')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='created_time')),
            ],
        ),
    ]
