# Generated by Django 5.0.3 on 2024-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriemodel',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_time'),
        ),
    ]
