# Generated by Django 5.0.3 on 2024-03-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_caloriemodel_calorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caloriemodel',
            options={'verbose_name': 'CalorieModel', 'verbose_name_plural': 'CalorieModels'},
        ),
        migrations.AlterModelTable(
            name='caloriemodel',
            table='caloriemodel',
        ),
    ]
